# This file was generated by GoReleaser. DO NOT EDIT.
cask "canaryctl" do
  version "0.4.17"

  on_macos do
    on_intel do
      sha256 "f371115b315b2d4a59ac8f033ad1340ff6f957db5b2dd444968a2cc3fc7117b3"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a458a5d3237d8cd69c77a3e1284bd8052dbb3df0d55f47432177ed9d32c0e7f4"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cfe1e2e856e1a4c7196d136ddf6581ae52894341f8c9affc3125517ef30efa68"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cba03735884206cd482366251c7be482bd011afe519fdb7de79ebb486ca7287a"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canaryctl"
  desc "canarybot CLI — drive canary rollouts over the REST API"
  homepage "https://github.com/alexremn/canarybot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canaryctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/canaryctl"]
    end
  end

  # No zap stanza required

end
