# This file was generated by GoReleaser. DO NOT EDIT.
cask "canaryctl" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "0df6fed33f6982962967dcd889f2bc290e61e3a23b93cb0c5ce8e9585610e2ee"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c40f4d65f47e321861a4fcd25a849f2b54e6b244b37e4443bfe275e36dca3f50"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7194fcceba9bdff634c603d09dd216886505e62ef89ec505c8434b548dc1dab"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ed583fba4b26122fdfe7a33989912b1f0135b56e8d88f2025cf258a9480d2fd"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canaryctl"
  desc "canarybot CLI — drive canary rollouts over the REST API"
  homepage "https://github.com/alexremn/canarybot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canaryctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/canaryctl"]
    end
  end

  # No zap stanza required

end
