# This file was generated by GoReleaser. DO NOT EDIT.
cask "canaryctl" do
  version "0.6.13"

  on_macos do
    on_intel do
      sha256 "92e0cfaa05d918f1e4b345d9cdbb3d8917364fad446aa97c71a7e3a503901744"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "158b72e9ca2fb157608853c34f19afbfc14aae6d6cf059e3cb78e98b0224c355"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16c7380d3babbfae5d77736ecd6e289bef8de1a79d705959f3cf39b53fd52a39"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9668454c84c524a091ee2de8a23a6eb6b95019ff06a04231ece9146c74725bcb"
      url "https://github.com/alexremn/canarybot/releases/download/v#{version}/canaryctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canaryctl"
  desc "canarybot CLI — drive canary rollouts over the REST API"
  homepage "https://github.com/alexremn/canarybot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canaryctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/canaryctl"]
    end
  end

  # No zap stanza required

end
