# This file was generated by GoReleaser. DO NOT EDIT.
cask "finalizer-doctor" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "2af39e33fb6216ee02e923b3a4aa079b1d2b49fbb958974b213adb5e8dd19b9a"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9c0c2abe35b74e248b9ea67eafa8c4206a5afbc2f05713726e103d9889fd536"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c4c39457c200007dfe59a136c73533ec924552751f930b4afb6ad686fcd80f70"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "818e488c0d2c02e5cbb6472df0d0c2974ad344b3850654ed601b09ac4a6dd93e"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_linux_amd64.tar.gz"
    end
  end

  name "finalizer-doctor"
  desc "Safely diagnose and clear finalizers on stuck-Terminating Kubernetes resources"
  homepage "https://github.com/alexremn/finalizer-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-finalizer_doctor"
  binary "kubectl-fid"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      ["kubectl-finalizer_doctor", "kubectl-fid"].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as kubectl plugins (both binaries are placed on your PATH):
      kubectl finalizer-doctor <target>
      kubectl fid <target>
  EOS
end
