# This file was generated by GoReleaser. DO NOT EDIT.
cask "finalizer-doctor" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "cfd8bcc95d81442ca14a699286a71c87aa57c748241b2a508c1db4b43f68d24d"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d20cb2af4d56f1f57ce8773219001ce0f6884f17810b0b2b2829aad970de8ad"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e0334acbb1902e04cec6945072aeab6922ff3720f0c8c11e677ed0067dd5ac2f"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc324713257216fef79bbb68b917356038be1b236f07ab67d7f3b452d8f6a6ed"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_linux_amd64.tar.gz"
    end
  end

  name "finalizer-doctor"
  desc "Safely diagnose and clear finalizers on stuck-Terminating Kubernetes resources"
  homepage "https://github.com/alexremn/finalizer-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-finalizer_doctor"
  binary "kubectl-fid"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      ["kubectl-finalizer_doctor", "kubectl-fid"].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as kubectl plugins (both binaries are placed on your PATH):
      kubectl finalizer-doctor <target>
      kubectl fid <target>
  EOS
end
