# This file was generated by GoReleaser. DO NOT EDIT.
cask "finalizer-doctor" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "fdaf76e0cf535b02f7ff7b81322da5679e6efb9edf58e52bca3af659ee616565"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92f8541f4a4f95b556149b6e61b33106eb403a2c54b7586ba6faa00d4d55750a"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e06393cb13b52b261c1aa6ef0ec69bb37aba83067c10fe95629e82097b70fb91"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d7d5a4f1828f30d3547368ed69e6bca525b8b7850dd1906224186fa18f2b6ba"
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v#{version}/finalizer-doctor_linux_arm64.tar.gz"
    end
  end

  name "finalizer-doctor"
  desc "Safely diagnose and clear finalizers on stuck-Terminating Kubernetes resources"
  homepage "https://github.com/alexremn/finalizer-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-finalizer_doctor"
  binary "kubectl-fid"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      ["kubectl-finalizer_doctor", "kubectl-fid"].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as kubectl plugins (both binaries are placed on your PATH):
      kubectl finalizer-doctor <target>
      kubectl fid <target>
  EOS
end
