# This file was generated by GoReleaser. DO NOT EDIT.
cask "keyspan" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "8226c26b868052ec15f4716d7159f39aa4a24b39ce95d78aafc83c76fe7c2786"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b836d344f32ef16f5dcc1542f24281cb7e66aae596011382650e1ae3b84046a1"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "12e6b1b61eaac6a15db693939cbac3e96618d665d0695bfc8fd931f13b7d624c"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a435a156d193a08d316a454f0b51c3f2bfd80ae508b39cddedcc289bf4d62ec9"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "keyspan"
  desc "Secret blast-radius graph: if I rotate this credential, what breaks and who owns it?"
  homepage "https://github.com/alexremn/keyspan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keyspan"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/keyspan"]
    end
  end

  # No zap stanza required

end
