# This file was generated by GoReleaser. DO NOT EDIT.
cask "keyspan" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "1bbb3a0b639e19afc56c43d213249fb2e789de8ca641504ee825e03f208e96d4"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78c67b4fffa6c99336f72328ef36804fa575179f03f2b99923503c4ae4f6a71e"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d8e4c5ab2dd67f23906285c7617bc6e949591d8715443732fd08b7fe687636f4"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3135f95c6feb66781d40099b0e325f0546f4164cd06e65b3344c559469b066fe"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "keyspan"
  desc "Secret blast-radius graph: if I rotate this credential, what breaks and who owns it?"
  homepage "https://github.com/alexremn/keyspan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keyspan"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/keyspan"]
    end
  end

  # No zap stanza required

end
