# This file was generated by GoReleaser. DO NOT EDIT.
cask "keyspan" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "3f5382a80e54d291093d79c3eeea41c6bfc943968a79fd12926f8b82184118ae"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5018be1e55e66520348b2f9d47f9c544761300c289e5d7c65a325e36d175738"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f92ce91dc222a8fcef4155443dcfac989425d9586ab2f6d7e6d568487a61a69"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3093ae8a5ddc2a178dbd967ccb3e437db609e3c00dbcecb7cb7f42cccb57ba6b"
      url "https://github.com/alexremn/keyspan/releases/download/v#{version}/keyspan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "keyspan"
  desc "Secret blast-radius graph: if I rotate this credential, what breaks and who owns it?"
  homepage "https://github.com/alexremn/keyspan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keyspan"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/keyspan"]
    end
  end

  # No zap stanza required

end
