# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-fieldlord" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ae132b6d4e69bda575ab9db7b6d36f6ca21c517df2a016afc4ad3d274630af42"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c35c731df9b6844b417c87ebfa64b5ed1663f4d165aec4da9fb5304edfba166"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ac98e761a3c44e89f48a927cb0b591181b3c3edb6f7f5c27ae234a245e954af"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d594799d6c0b943244b3f5cdcbe0bd405bf7e3efc2accf7a6971bc8d93b4f29"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_linux_arm64.tar.gz"
    end
  end

  name "kubectl-fieldlord"
  desc "Explain Server-Side Apply field ownership, drift, and clobber risk"
  homepage "https://github.com/alexremn/kubectl-fieldlord"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-fieldlord"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-fieldlord"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a kubectl plugin on your PATH:
      kubectl fieldlord explain <resource>
  EOS
end
