# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-fieldlord" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "3bc4bef823a9649d85b4cab24a7923907041d34dd12a4d381111d647e169ede5"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ddd7babe28c18b4399c475e1e53e582f2a820f1f50154b5ce8b65d21d84b386c"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6b70dbd7990636cf3f8790a9aeae2f42af3f7ac7b3134fb1b4d387a57f1ddb6d"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb3f65ad206277b8a025cef55c27877dd0fd8e2ce2d2cd3852274b4e0133762d"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_linux_amd64.tar.gz"
    end
  end

  name "kubectl-fieldlord"
  desc "Explain Server-Side Apply field ownership, drift, and clobber risk"
  homepage "https://github.com/alexremn/kubectl-fieldlord"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-fieldlord"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-fieldlord"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a kubectl plugin on your PATH:
      kubectl fieldlord explain <resource>
  EOS
end
