# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-fieldlord" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "309176d331f9181c7058ed810167bb70446dd79cf1e293bea220547f9ba96a66"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "32cd9fecde219c8eeb2ba8ea96f7d1ccfbb0eee315b18a98f88d8647e43ee5e2"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5e94e6724b0d97b9ac4335f0b96650b41309e8404864e8740c792cf23b788a0"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7d1eafa2114deaacc6bd2e4ea83bc060d1f43ac34baed52196a520dec40502a"
      url "https://github.com/alexremn/kubectl-fieldlord/releases/download/v#{version}/kubectl-fieldlord_linux_amd64.tar.gz"
    end
  end

  name "kubectl-fieldlord"
  desc "Explain Server-Side Apply field ownership, drift, and clobber risk"
  homepage "https://github.com/alexremn/kubectl-fieldlord"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-fieldlord"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-fieldlord"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a kubectl plugin on your PATH:
      kubectl fieldlord explain <resource>
  EOS
end
