# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FinalizerDoctor < Formula
  desc "Safely diagnose and clear finalizers on stuck-Terminating Kubernetes resources"
  homepage "https://github.com/alexremn/finalizer-doctor"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.1/finalizer-doctor_darwin_amd64.tar.gz"
      sha256 "ada71878f4ecfa9436c0844214d0fab1f667a1901e53c00a242d89e2afaa7525"

      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.1/finalizer-doctor_darwin_arm64.tar.gz"
      sha256 "f9deb3a31c697b48f4cd9f99bb5502cc7e5973c2698df0cf175719f05636c20f"

      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.1/finalizer-doctor_linux_amd64.tar.gz"
      sha256 "400604029eaaf909a235b7e8045262d68344dbc565d58f18cf44f8db799abec3"
      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.1/finalizer-doctor_linux_arm64.tar.gz"
      sha256 "58d4a74b22e45694dfbc801d8bc141329b84da4adfd6d47cf2a6a9f84fdba5e1"
      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
  end

  def caveats
    <<~EOS
      Installed as kubectl plugins (both binaries are placed on your PATH):
        kubectl finalizer-doctor <target>
        kubectl fid <target>
    EOS
  end

  test do
    system "#{bin}/kubectl-finalizer_doctor", "version"
  end
end
