# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FinalizerDoctor < Formula
  desc "Safely diagnose and clear finalizers on stuck-Terminating Kubernetes resources"
  homepage "https://github.com/alexremn/finalizer-doctor"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_darwin_amd64.tar.gz"
      sha256 "c47dd4e0a49c4c42f0972601ae8f97f9cb01cdc6c6dd8254b31bcab10d36c5c8"

      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_darwin_arm64.tar.gz"
      sha256 "624c7501c1e3ebff5aa08036624393c256b9d04433121cc9c62a699225933594"

      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_linux_amd64.tar.gz"
      sha256 "ad4823224a25ce358ce729fa370f77e709c96a8077466fca4542a052ea916f2c"
      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_linux_arm64.tar.gz"
      sha256 "ea345fd87497af44ad2f2649a75c3c2695c9040cdba52a33c7e4e45dc9855dfc"
      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
  end

  def caveats
    <<~EOS
      Installed as kubectl plugins (both binaries are placed on your PATH):
        kubectl finalizer-doctor <target>
        kubectl fid <target>
    EOS
  end

  test do
    system "#{bin}/kubectl-finalizer_doctor", "version"
  end
end
