# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FinalizerDoctor < Formula
  desc "Safely diagnose and clear finalizers on stuck-Terminating Kubernetes resources"
  homepage "https://github.com/alexremn/finalizer-doctor"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_darwin_amd64.tar.gz"
      sha256 "f8cdf3c7f6c07adcd9b305cc820049a2d8e4fe46696a6771e1ed59eae8a28308"

      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_darwin_arm64.tar.gz"
      sha256 "c874296549015bca79dc1ca9ee76a181f6071d8b71c9f115c7fba1f51e845f02"

      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_linux_amd64.tar.gz"
      sha256 "a06c549d5fbc93550397d5ae7872cd23b17edfa274fdf5a163450b7a4c3d418b"
      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexremn/finalizer-doctor/releases/download/v0.1.0/finalizer-doctor_linux_arm64.tar.gz"
      sha256 "77ff34685c63f1102fd9707b6e54c204475a9d193dcaab32c4329bf02bb8ea4f"
      define_method(:install) do
        bin.install "kubectl-finalizer_doctor"
        bin.install "kubectl-fid"
      end
    end
  end

  def caveats
    <<~EOS
      Installed as kubectl plugins (both binaries are placed on your PATH):
        kubectl finalizer-doctor <target>
        kubectl fid <target>
    EOS
  end

  test do
    system "#{bin}/kubectl-finalizer_doctor", "version"
  end
end
